package com.dentis.domain.enums;

public enum NotificationType {
    APPOINTMENT_CONFIRMATION,
    APPOINTMENT_REMINDER,
    APPOINTMENT_CANCELLATION,
    APPOINTMENT_RESCHEDULED,
    PAYMENT_RECEIVED,
    TREATMENT_UPDATE,
    INTERNAL_ADMIN
}
